# Site
repository: deadbits/deadbits.github.io
# favicon: images/favicon.ico

# Personal info
name: Adam M. Swanda
title: Principal Threat Intelligence Analyst
email: adam@deadbits.org
website: www.deadbits.org

# Social links
twitter_username: bindshell_
github_username:  deadbits
instagram_username: deadbits_
linkedin_username: adamswanda

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Adam and I'm a hacker. I currently live in the Washinton D.C. metro area where I hunt and stop bad guys as a Principal Threat Intelligence Analyst at a pretty cool technology company. Outside of work I love to develop new projects in Python, write short fiction stories, sketch/draw/paint in all sorts of ways (pencil, charcoal, pastels, etc.), and occasionally do the whole "outdoors" things people seem to be raving about.

  I am highly proficient in: <mark>Threat Intelligence</mark>, <mark>Malware Analysis & Reverse Engineering</mark>, and <mark>Python development.</mark>

# Projects Section
#projects_title: Projects
#- name: Omnibus
#  link: github.com/InQuest/Omnibus
#  github: github.com/InQuest/Omnibus
#  quote: >
#    Omnibus is a plugin based framework for OSINT (Open-source intelligence) artifact management, collection, and research.
#  description: |
#    An Omnibus is typically a volume containing several novels or other items previously published separately. That is exactly what this project intends to be for OSINT collection, research, and artifact management.
#    With an easy to use interactive command line interface, users are able to create sessions to investigate various artifacts such as IP addresses, domain names, email addresses, user names, file hashes, Bitcoin addresses, and even more as the project continues to grow. Since the platform is built in a modular fashion, it is simple to add new functionality and have users create their own custom modules.

# Experience Section
# experience_title: Experience
#- company: Splunk Inc.
#  job_title: Principal Threat Intelligence Analyst
#  dates: November 2018 to present
#  description: |
#    Threat intelligence is a must-have for mature organizations, and Splunk is no exception. I focus on researching bad actors and create various ways to mitigate risk to the company, the employees, and customers; whether that's through proactive monitoring, threat hunting, RFIs, intelligence alerts, or any other number of processes.

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  When I'm not hunting bad guys or writing code, some of my other interests and hobbies are:
   - Writing short stories
   - Sketching
   - Painting (pastels)
   - 3D Printing
   - Playing with IoT devices
   - Reading/studying finance and machine learning
   - Napping

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
