# Site
repository: deadbits/deadbits.github.io
favicon: images/favicon.ico

# Personal info
name: Adam M. Swanda
title: Principal Threat Intelligence Analyst
email: adam@deadbits.org
website: www.deadbits.org

# Social links
twitter_username: bindshell_
github_username:  deadbits
instagram_username: deadbits_
linkedin_username: adamswanda

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Adam and I'm a hacker. I currently live in the Washinton D.C. metro area I work as a Principal Threat Intelligence Analyst at a pretty cool technology company.

  I am highly proficient in: <mark>Threat Intelligence</mark>, <mark>Malware Analysis & Reverse Engineering</mark>, and <mark>Python development.</mark>

  When I'm not hunting bad guys or writing code, some of my other interests and hobbies are:
   - Writing short fiction stories
   - Sketching (pencil, charcoals)
   - Painting (pastels)
   - 3D Printing
   - Playing with IoT devices
   - Studying & developing tools around the intersection of finance and machine learning
   - Napping

# Projects Section
#projects_title: Projects

# Experience Section
#experience_title: Experience

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
